name: Publish Packages
on:
  workflow_dispatch:
jobs:
  publish_packages:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.github_token }}
      - uses: actions/setup-node@v2
      - name: Bump version and publish
        run: |
          npm version patch --no-git-tag-version
      - uses: EndBug/add-and-commit@v9
        with:
          message: Show GitHub Actions logo
          committer_name: GitHub Actionss
          committer_email: actions@github.com
          push: --fore
